language: elixir
sudo: false
env:
  global:
    - GPGME_DEBUG=9
    - AUTOMAKE_VERSION=1.14.1
    - GETTEXT_VERSION=0.19.3
    - MIX_ENV=test
addons:
  apt:
    packages:
      - autoconf
      - automake
      - gettext
      - openssl
elixir:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 20.0
script: mix test --cover
before_install:
  - curl https://sh.rustup.rs | sh -s -- -y
  - export PATH="$HOME/.cargo/bin:$PATH"
cache:
  directories:
    - ~/.mix
    - ~/.hex
jobs:
  include:
    - stage: format
      env:
        - MIX_ENV=dev
      script: mix format --check-formatted
      elixir: 1.8
    - stage: credo
      env:
        - MIX_ENV=dev
      script: mix credo --strict
      elixir: 1.8
    - stage: dialyzer
      env:
        - MIX_ENV=dev
      before_script: travis_wait mix dialyzer --plt
      script: mix dialyzer --halt-exit-status
      elixir: 1.8
    - stage: inch
      env:
        - MIX_ENV=docs
      script: mix inch.report
      elixir: 1.8
